-- Comic Library schema reference
-- Jalankan di Neon jika tabel belum tersedia.

CREATE TABLE kategori (
    id INT PRIMARY KEY,
    nama_kategori VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE genre (
    id INT PRIMARY KEY,
    nama_genre VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE komik (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    kategori_id INT,
    genre_id INT,
    reading_status VARCHAR(50) NOT NULL
        CHECK (reading_status IN (
            'Planning read',
            'Reading',
            'On Hold',
            'Completed'
        )),
    komik_status VARCHAR(50) NOT NULL
        CHECK (komik_status IN (
            'On Going',
            'Completed',
            'Waiting New Season',
            'Gatau baca dimana'
        )),
    rating DECIMAL(3,1)
        CHECK (rating >= 0 AND rating <= 10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_kategori
        FOREIGN KEY (kategori_id)
        REFERENCES kategori(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_genre
        FOREIGN KEY (genre_id)
        REFERENCES genre(id)
        ON DELETE SET NULL
);
