syntax = "proto3";

package komiklib;

// Message entitas Komik
message Komik {
  int32 id = 1;
  string judul = 2;
  int32 kategori_id = 3;
  int32 genre_id = 4;
  string reading_status = 5;
  string komik_status = 6;
  float rating = 7;
  string created_at = 8;
  string updated_at = 9;
}

// Request & Response Read
message GetKomikRequest {
  int32 id = 1;
}

message GetKomikResponse {
  Komik komik = 1;
}

message EmptyRequest {
}

message ListKomikResponse {
  repeated Komik komiks = 1;
}

// Request Create
message CreateKomikRequest {
  string judul = 1;
  int32 kategori_id = 2;
  int32 genre_id = 3;
  string reading_status = 4;
  string komik_status = 5;
  float rating = 6;
}

// Request Update
message UpdateKomikRequest {
  int32 id = 1;
  string judul = 2;
  int32 kategori_id = 3;
  int32 genre_id = 4;
  string reading_status = 5;
  string komik_status = 6;
  float rating = 7;
}

// Request & Response Delete
message DeleteKomikRequest {
  int32 id = 1;
}

message DeleteKomikResponse {
  bool success = 1;
}

// Service gRPC Lengkap (CRUD)
service KomikService {
  rpc GetKomikById (GetKomikRequest) returns (GetKomikResponse);
  rpc GetAllKomik (EmptyRequest) returns (ListKomikResponse);
  rpc CreateKomik (CreateKomikRequest) returns (GetKomikResponse);
  rpc UpdateKomik (UpdateKomikRequest) returns (GetKomikResponse);
  rpc DeleteKomik (DeleteKomikRequest) returns (DeleteKomikResponse);
}
